name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn build-es3
      - run: yarn build-es6
      - run: yarn test
