name: publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node v18.x
        uses: actions/setup-node@v2
        with:
          node-version: 'v18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn build:es3
      - run: yarn build:es6
      - run: yarn test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}