name: publish-docs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: yarn install
      - run: yarn docs-build
      - name: publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: lib-docs